In [1]:
# Import libraries
import pandas as pd
import numpy as np

In [2]:
# Load dataset
df = pd.read_csv(r"../data/heart_disease_dataset.csv")
# Display first 5 rows
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,69,1,0,160,234,1,2,131,0,0.1,1,1,0,0
1,69,0,0,140,239,0,0,151,0,1.8,0,2,0,0
2,66,0,0,150,226,0,0,114,0,2.6,2,0,0,0
3,65,1,0,138,282,1,2,174,0,1.4,1,1,0,1
4,64,1,0,110,211,0,2,144,1,1.8,1,0,0,0

In [3]:
#Rename columns
df.rename(columns={
    'age': 'Age',
    'sex': 'Gender',
    'cp': 'Chest_Pain_Type',
    'trestbps': 'Resting_Blood_Pressure',
    'chol': 'Cholesterol',
    'fbs': 'Fasting_Blood_Sugar',
    'restecg': 'Resting_ECG',
    'thalach': 'Max_Heart_Rate',
    'exang': 'Exercise_Induced_Angina',
    'oldpeak': 'ST_Depression',
    'slope': 'ST_Slope',
    'ca': 'Major_Vessels',
    'thal': 'Thalassemia',
    'condition': 'Heart_Disease'
}, inplace=True)
df.rename(columns={'Sex': 'Gender'}, inplace=True)

In [4]:
df.info()   #check Info

<class 'pandas.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      297 non-null    int64
 1   Gender                   297 non-null    int64
 2   Chest_Pain_Type          297 non-null    int64
 3   Resting_Blood_Pressure   297 non-null    int64
 4   Cholesterol              297 non-null    int64
 5   Fasting_Blood_Sugar      297 non-null    int64
 6   Resting_ECG              297 non-null    int64
 7   Max_Heart_Rate           297 non-null    int64
 8   Exercise_Induced_Angina  297 non-null    int64
 9   ST_Depression            297 non-null    float64
 10  ST_Slope                 297 non-null    int64
 11  Major_Vessels            297 non-null    int64
 12  Thalassemia              297 non-null    int64
 13  Heart_Disease            297 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 32.6 KB

In [5]:
#Check shape
print("Rows and Columns:", df.shape)
#CHECK DATA TYPES
print("\nData Types:")
print(df.dtypes)

Rows and Columns: (297, 14)

Data Types:
Age                          int64
Gender                       int64
Chest_Pain_Type              int64
Resting_Blood_Pressure       int64
Cholesterol                  int64
Fasting_Blood_Sugar          int64
Resting_ECG                  int64
Max_Heart_Rate               int64
Exercise_Induced_Angina      int64
ST_Depression              float64
ST_Slope                     int64
Major_Vessels                int64
Thalassemia                  int64
Heart_Disease                int64
dtype: object

In [6]:
#check missing value
df.isnull().sum()

Age                        0
Gender                     0
Chest_Pain_Type            0
Resting_Blood_Pressure     0
Cholesterol                0
Fasting_Blood_Sugar        0
Resting_ECG                0
Max_Heart_Rate             0
Exercise_Induced_Angina    0
ST_Depression              0
ST_Slope                   0
Major_Vessels              0
Thalassemia                0
Heart_Disease              0
dtype: int64

In [7]:
#check duplicate rows
df.duplicated().sum()
#Remove Duplicates
df.drop_duplicates(inplace=True)

In [9]:
# Numerical columns
numerical_cols = [
    'Age',
    'Resting_Blood_Pressure',
    'Cholesterol',
    'Max_Heart_Rate',
    'ST_Depression',
    'Major_Vessels'
]

# Fill missing values using median imputation
for col in numerical_cols:
    df[col] = df[col].fillna(df[col].median())

In [10]:
#handle missing values in categorical columns
categorical_cols = [
    'Gender',
    'Chest_Pain_Type',
    'Fasting_Blood_Sugar',
    'Resting_ECG',
    'Exercise_Induced_Angina',
    'ST_Slope',
    'Thalassemia',
    'Heart_Disease'
]

#USING MODE IMPUTATION
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [11]:
#Verify missing values
df.isnull().sum()

Age                        0
Gender                     0
Chest_Pain_Type            0
Resting_Blood_Pressure     0
Cholesterol                0
Fasting_Blood_Sugar        0
Resting_ECG                0
Max_Heart_Rate             0
Exercise_Induced_Angina    0
ST_Depression              0
ST_Slope                   0
Major_Vessels              0
Thalassemia                0
Heart_Disease              0
dtype: int64

In [12]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [13]:
#Summary statistics
df.describe()

,Age,Gender,Chest_Pain_Type,Resting_Blood_Pressure,Cholesterol,Fasting_Blood_Sugar,Resting_ECG,Max_Heart_Rate,Exercise_Induced_Angina,ST_Depression,ST_Slope,Major_Vessels,Thalassemia,Heart_Disease
count,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000
mean,54.542088,0.676768,2.158249,131.693603,247.350168,0.144781,0.996633,149.599327,0.326599,1.055556,0.602694,0.676768,0.835017,0.461279
std,9.049736,0.468500,0.964859,17.762806,51.997583,0.352474,0.994914,22.941562,0.469761,1.166123,0.618187,0.938965,0.956690,0.499340
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,2.000000,120.000000,211.000000,0.000000,0.000000,133.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,56.000000,1.000000,2.000000,130.000000,243.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,0.000000,0.000000
75%,61.000000,1.000000,3.000000,140.000000,276.000000,0.000000,2.000000,166.000000,1.000000,1.600000,1.000000,1.000000,2.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,3.000000,2.000000,1.000000

In [14]:
#Check data types
df.dtypes

Age                          int64
Gender                       int64
Chest_Pain_Type              int64
Resting_Blood_Pressure       int64
Cholesterol                  int64
Fasting_Blood_Sugar          int64
Resting_ECG                  int64
Max_Heart_Rate               int64
Exercise_Induced_Angina      int64
ST_Depression              float64
ST_Slope                     int64
Major_Vessels                int64
Thalassemia                  int64
Heart_Disease                int64
dtype: object

In [15]:
df.to_csv(r"../data/cleaned_heart_disease_dataset.csv", index=False)